[package]
name = "sarmg-platform-events"
description = "Transport-neutral event API for Sarmg plugins"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
